
# what even is a database :nerd:?


# the ocref command
oc_info = {
    "Clouds": {
        "short_description": "cloudy",
        "emoji": "☁",

        "description": "cloudy",
        "side_color": 0x72bae0,  # remember to change the # to 0x (for example #72bae0 -> 0x72bae0)
        "created_by": "someone",
        "created_on": "tomorrow",
        "image": "https://media.discordapp.net/attachments/859952810282844222/1059709900307050496/C1714498-5D45-4459-9EDC-E6B80549DC0F.png?width=510&height=390"
    },
    "Rain": {
        "short_description": "rainy",
        "emoji": "🌧️",

        "description": "rainy",
        "side_color": 0x444f54,
        "created_by": "me",
        "created_on": "1984",
        "image": "https://media.discordapp.net/attachments/997643106855960627/1056348872915554304/FkwZPRpXwAI50Fj.jpg?width=376&height=390"
    }
}

# pope
quote_translation = {
    "papiez": "pope",
    "tak": "yes",
    "Tak jak pan Jezus powiedział": "Just like the Lord Jesus said"
}

# the what command
texts = (
    "A BAGFUL OF WHITE COTTON",
    "ONE THICK SEWING NEEDLE",
    "LOTS AND LOTS OF LITTLE PINS",
    "A PAIR OF RUSTY SCISSORS",
    "A TOMATO MADE OF CLOTH",
    "TWO YARDS OF LEATHER",
    "A PAIR OF BIG BEAUTIFUL BUTTONS",
    "A SMALL WOODEN TABLE"
)

# the goober command
goobers = (
    "https://media.discordapp.net/attachments/894855956729581591/1057365335453466704/image0-27-1.gif",
    "https://tenor.com/view/tudou-gif-23761920",
    "https://imgur.com/a/lO4C8VN",
    "https://tenor.com/view/candy-cane-cat-cat-cane-cat-smell-gif-21923821",
    "https://cdn.discordapp.com/attachments/367834588753690655/1055953054966485022/9B052C19-2948-4C58-8C78-1856E0B5815D.gif",
    "https://tenor.com/view/cat-calico-sleeping-cute-gif-18816974",
    "https://tenor.com/view/cat-cat-stare-stare-wtf-whatever-gif-25183190",
    "https://media.discordapp.net/attachments/1033144669514760204/1048999097538969671/ED37008E-112C-4B8C-AC09-1B40913898C0.gif",
    "https://tenor.com/view/goober-cat-tongue-discord-gif-26536949",
    "https://tenor.com/view/blahaj-cat-gif-26619752",
    "https://tenor.com/view/cat-gif-26293253",
    "https://tenor.com/view/stare-staring-cat-gif-20275090",
    "https://tenor.com/view/cat-cute-pet-animal-paw-gif-17624352",
    "https://tenor.com/view/glumper-cat-eat-graham-cracker-cat-cute-cat-gif-26516023",
    "https://tenor.com/view/loaf-cat-messages-from-the-stars-pog-cat-gif-25242094",
    "https://media.discordapp.net/attachments/834312139559927828/1028337878243233792/caption.gif",
    "https://tenor.com/view/cat-watermelon-eating-eats-eat-gif-25258999",
    "https://tenor.com/view/cat-cats-corn-gif-24417734",
    "https://tenor.com/view/wawa-wawa-cat-gif-26059883",
    "https://tenor.com/view/bonk-funny-cat-bonk-bonk-bonk-bonk-bonk-bonk-bonk-cat-funny-hammer-gif-22703304",
    "https://media.discordapp.net/attachments/637405139992576020/1000046192648015892/caption-36.gif",
    "https://imgur.com/a/oo8pgti",
    "https://tenor.com/view/you-have-alerted-the-cat-cat-has-been-alerted-gif-26351872",
    "https://tenor.com/view/cat-cat-standing-cat-stare-stare-bruhcat-gif-22348277",
    "https://tenor.com/view/cat-angry-meme-aggression-confusion-gif-22568593",
    "This message has 1/25 (4%) chances of appearing! Enjoy!"
)

# the translate command
lang_codes = {
    'afar': 'aa',
    'bangla': 'bn',
    'abkhazian': 'ab',
    'bambara': 'bm',
    'belarusian': 'be',
    'bashkir': 'ba',
    'azerbaijani': 'az',
    'aymara': 'ay',
    'avaric': 'av',
    'assamese': 'as',
    'arabic': 'ar',
    'aragonese': 'an',
    'amharic': 'am',
    'akan': 'ak',
    'afrikaans': 'af',
    'avestan': 'ae',
    'bulgarian': 'bg',
    'tibetan': 'bo',
    'bislama': 'bi',
    'breton': 'br',
    'bosnian': 'bs',
    'catalan': 'ca',
    'wolof': 'wo',
    'walloon': 'wa',
    'volapük': 'vo',
    'vietnamese': 'vi',
    'venda': 've',
    'uzbek': 'uz',
    'urdu': 'ur',
    'ukrainian': 'uk',
    'uyghur': 'ug',
    'tahitian': 'ty',
    'twi': 'tw',
    'tatar': 'tt',
    'tsonga': 'ts',
    'turkish': 'tr',
    'tongan': 'to',
    'tswana': 'tn',
    'tagalog': 'tl',
    'turkmen': 'tk',
    'tigrinya': 'ti',
    'thai': 'th',
    'tajik': 'tg',
    'telugu': 'te',
    'tamil': 'ta',
    'swahili': 'sw',
    'swedish': 'sv',
    'sundanese': 'su',
    'southern sotho': 'st',
    'swati': 'ss',
    'serbian': 'sr',
    'albanian': 'sq',
    'somali': 'so',
    'shona': 'sn',
    'samoan': 'sm',
    'slovenian': 'sl',
    'slovak': 'sk',
    'sinhala': 'si',
    'serbo-croatian': 'sh',
    'sango': 'sg',
    'northern sami': 'se',
    'sindhi': 'sd',
    'sardinian': 'sc',
    'sanskrit': 'sa',
    'kinyarwanda': 'rw',
    'russian': 'ru',
    'romanian': 'ro',
    'rundi': 'rn',
    'romansh': 'rm',
    'quechua': 'qu',
    'portuguese': 'pt',
    'pashto': 'ps',
    'polish': 'pl',
    'pali': 'pi',
    'punjabi': 'pa',
    'ossetic': 'os',
    'odia': 'or',
    'oromo': 'om',
    'ojibwa': 'oj',
    'occitan': 'oc',
    'nyanja': 'ny',
    'navajo': 'nv',
    'south ndebele': 'nr',
    'norwegian': 'no',
    'norwegian nynorsk': 'nn',
    'dutch': 'nl',
    'ndonga': 'ng',
    'nepali': 'ne',
    'north ndebele': 'nd',
    'norwegian bokmål': 'nb',
    'nauru': 'na',
    'burmese': 'my',
    'maltese': 'mt',
    'malay': 'ms',
    'marathi': 'mr',
    'mongolian': 'mn',
    'malayalam': 'ml',
    'macedonian': 'mk',
    'maori': 'mi',
    'marshallese': 'mh',
    'malagasy': 'mg',
    'latvian': 'lv',
    'luba-katanga': 'lu',
    'lithuanian': 'lt',
    'lao': 'lo',
    'lingala': 'ln',
    'limburgish': 'li',
    'ganda': 'lg',
    'luxembourgish': 'lb',
    'latin': 'la',
    'kyrgyz': 'ky',
    'cornish': 'kw',
    'komi': 'kv',
    'kurdish': 'ku',
    'kashmiri': 'ks',
    'kanuri': 'kr',
    'korean': 'ko',
    'kannada': 'kn',
    'khmer': 'km',
    'kalaallisut': 'kl',
    'kazakh': 'kk',
    'kuanyama': 'kj',
    'kikuyu': 'ki',
    'kongo': 'kg',
    'georgian': 'ka',
    'javanese': 'jv',
    'japanese': 'ja',
    'inuktitut': 'iu',
    'italian': 'it',
    'icelandic': 'is',
    'ido': 'io',
    'inupiaq': 'ik',
    'sichuan yi': 'ii',
    'igbo': 'ig',
    'interlingue': 'ie',
    'indonesian': 'id',
    'interlingua': 'ia',
    'herero': 'hz',
    'armenian': 'hy',
    'hungarian': 'hu',
    'haitian creole': 'ht',
    'croatian': 'hr',
    'hiri motu': 'ho',
    'hindi': 'hi',
    'hebrew': 'he',
    'hausa': 'ha',
    'manx': 'gv',
    'gujarati': 'gu',
    'guarani': 'gn',
    'galician': 'gl',
    'scottish gaelic': 'gd',
    'irish': 'ga',
    'western frisian': 'fy',
    'french': 'fr',
    'faroese': 'fo',
    'fijian': 'fj',
    'finnish': 'fi',
    'fulah': 'ff',
    'persian': 'fa',
    'basque': 'eu',
    'estonian': 'et',
    'spanish': 'es',
    'esperanto': 'eo',
    'english': 'en',
    'greek': 'el',
    'ewe': 'ee',
    'dzongkha': 'dz',
    'divehi': 'dv',
    'german': 'de',
    'danish': 'da',
    'welsh': 'cy',
    'chuvash': 'cv',
    'church slavic': 'cu',
    'czech': 'cs',
    'cree': 'cr',
    'corsican': 'co',
    'chamorro': 'ch',
    'chechen': 'ce',
    'zulu': 'zu',
    'zhuang': 'za',
    'xhosa': 'xh',
    'yoruba': 'yo',
    'yiddish': 'yi',
    'chinese': 'zh'}
